
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 135
#define YY_END_OF_BUFFER 136
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[450] =
    {   0,
        0,    0,  136,  135,    1,  135,  135,    8,  135,  135,
      135,    6,    6,  134,  134,  134,  135,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,    1,    2,    0,
        6,    0,    0,    0,    6,    6,    0,    6,    6,  134,
      134,  134,    0,   12,  134,    9,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,

      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,    0,   11,
       11,    5,    7,    0,  134,  134,  134,  134,   13,  134,
      134,   54,  134,  134,  134,  134,   65,  134,  134,  134,
      134,  134,  134,   15,  134,  134,  134,  134,  134,  134,
       68,   25,  134,  134,  121,   69,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,   34,  134,  134,
      128,  134,  134,  134,  134,  134,  134,  134,  134,  134,
       79,  134,   81,  134,  134,  134,  134,  134,  134,  134,

      134,   44,  134,  134,  134,  134,  134,  134,  134,  134,
       96,  134,  134,  134,  134,  134,  134,  134,  101,  134,
       51,  134,  134,  134,  134,  134,  134,  134,   14,  134,
      134,  134,   53,  134,    0,    5,    0,  134,  134,  134,
      134,  134,  134,   63,  134,  112,   64,  134,  134,  134,
      134,  134,  118,  134,  134,  134,  134,   24,  134,   67,
      134,  134,   28,  134,  134,  134,  134,  134,  134,  134,
       32,   16,   33,  134,  134,  134,  134,  134,  134,  134,
      134,  134,   38,  122,  134,  134,  134,   41,  134,   80,
       82,  134,  117,   84,  134,  134,  134,  134,  134,  134,

       92,  134,  134,   45,  119,  134,  134,   59,  134,  134,
      134,   49,  134,  134,  134,   50,  100,  103,  134,  134,
      134,  105,  133,  134,  134,  107,  134,  134,  134,  134,
      134,  134,    0,    0,  110,  134,  115,  116,   62,  111,
      134,   17,   18,  134,   20,  134,   66,  130,   22,  134,
      134,   26,   27,  126,   29,   30,   31,  124,   60,  134,
       70,  134,  134,   36,  134,   72,   73,   74,   75,   76,
       77,   37,   39,   56,   40,   58,   78,  134,  134,   86,
       87,   88,   89,   90,   91,   42,   43,   93,   46,   47,
      134,  134,   95,   97,  134,  134,   99,  102,  134,  104,

      134,   61,  127,  134,  134,  134,  134,  109,  134,    4,
        0,  134,  134,   19,   21,   23,  134,   57,  134,   35,
      134,  134,   85,   48,   94,  125,  134,   55,  106,  134,
      134,  108,   52,  134,    3,  113,  114,  120,  134,   71,
       83,   98,  134,  131,  123,  134,  132,  129,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    5,    6,    7,    8,    9,   10,   11,   12,
       12,   12,   12,   12,   12,   13,   13,    1,    9,    1,
        1,    1,    1,    1,   14,   15,   14,   14,   14,   14,
       16,   16,   16,   16,   16,   17,   16,   16,   16,   16,
       16,   16,   16,   16,   18,   16,   16,   16,   16,   16,
        1,    9,    1,   19,   20,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   16,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[46] =
    {   0,
        1,    1,    2,    1,    1,    3,    3,    3,    3,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    5,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4
    } ;

static yyconst flex_int16_t yy_base[455] =
    {   0,
        0,    0,  137, 2064,   44,    0,   40,  121,   46,   50,
      118,   58,   90,   66,   69,   77,  107,    0,  120,  153,
      171,  204,  220,   79,   82,  109,   80,  240,  142,  110,
      256,   96,  143,  273,  194,  155,  196,   81,    0,   81,
      227,  115,   78,  297,  308,  312,  316,  167,    0,  160,
        0,  347,  323,  330,  337, 2064,  226,  350,  201,  248,
      161,  243,  326,  353,  360,  363,  274,  369,  389,  372,
      379,  388,  405,  398,  411,  410,  423,  424,  429,  432,
      431,  445,  448,  450,  451,  458,  467,  479,  480,  481,
      493,  487,  505,  506,  507,  523,  513,  526,  514,  535,

      542,  551,  552,  554,  560,  559,  561,  578,  579,  584,
      585,  606,  605,  608,  613,  614,  626,  631,  636,  648,
      645,  650,  658,  668,  667,  670,  675,  676,  106,  707,
      711,  320,    0,  715,  704,  705,  707,  712,  713,  725,
      737,  732,  734,  739,  744,  757,  756,  762,  769,  770,
      782,  776,  788,  789,  790,  795,  811,  802,  808,  818,
      820,  821,  827,  828,  830,  837,  840,  847,  853,  846,
      860,  863,  865,  873,  872,  879,  882,  889,  891,  898,
      899,  901,  917,  907,  924,  927,  930,  933,  947,  949,
      950,  955,  956,  957,  974,  975,  977,  996,  976,  984,

     1001, 1006, 1008, 1013, 1020, 1025, 1030, 1022, 1042, 1047,
     1054, 1055, 1056, 1063, 1068, 1076, 1073, 1081, 1089, 1094,
     1095, 1101, 1102, 1107, 1119, 1124, 1125, 1133, 1132, 1141,
     1142, 1149, 1151, 1154,  105,  395, 1185, 1161, 1177, 1178,
     1179, 1185, 1191, 1186, 1198, 1199, 1205, 1207, 1217, 1219,
     1224, 1225, 1226, 1227, 1244, 1246, 1249, 1247, 1252, 1254,
     1266, 1271, 1273, 1278, 1276, 1279, 1296, 1297, 1299, 1302,
     1304, 1316, 1318, 1323, 1332, 1325, 1341, 1342, 1344, 1350,
     1351, 1363, 1368, 1369, 1371, 1376, 1388, 1389, 1395, 1390,
     1396, 1397, 1402, 1409, 1414, 1415, 1421, 1423, 1416, 1428,

     1440, 1441, 1442, 1448, 1449, 1458, 1474, 1461, 1466, 1479,
     1480, 1486, 1488, 1493, 1502, 1505, 1507, 1510, 1519, 1526,
     1529, 1528, 1531, 1549, 1536, 1548, 1550, 1556, 1558, 1570,
     1572, 1575, 1606,   66, 1580, 1600, 1597, 1598, 1599, 1605,
     1606, 1607, 1619, 1624, 1625, 1627, 1632, 1637, 1644, 1645,
     1646, 1651, 1653, 1658, 1663, 1665, 1670, 1671, 1672, 1677,
     1684, 1693, 1690, 1691, 1700, 1698, 1703, 1710, 1712, 1717,
     1719, 1720, 1722, 1729, 1736, 1738, 1739, 1741, 1746, 1748,
     1755, 1760, 1762, 1765, 1767, 1768, 1774, 1781, 1784, 1786,
     1787, 1793, 1794, 1803, 1806, 1811, 1812, 1813, 1825, 1830,

     1832, 1833, 1835, 1853, 1851, 1852, 1854, 1860, 1870, 1856,
       45, 1872, 1873, 1880, 1882, 1889, 1892, 1890, 1902, 1908,
     1910, 1915, 1916, 1918, 1928, 1934, 1936, 1937, 1942, 1944,
     1950, 1956, 1958, 1966, 2064, 1963, 1968, 1975, 1976, 1984,
     1985, 1992, 1997, 1994, 2002, 2004, 2010, 2011, 2064, 2051,
     2054, 2056, 2058,   45
    } ;

static yyconst flex_int16_t yy_def[455] =
    {   0,
      449,    1,  449,  449,  449,  450,  449,  451,  451,  449,
      451,  452,  452,  452,   13,   13,  449,  453,   13,  452,
       19,  452,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,  449,  450,  449,
      449,  451,  449,  449,  451,  449,  454,   13,   13,   22,
      453,   22,  454,   13,   13,  449,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,  449,  454,
      454,   13,   52,  454,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,  449,   13,  449,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,  449,  449,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,   22,  449,
      449,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,  449,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,    0,  449,
      449,  449,  449,  449
    } ;

static yyconst flex_int16_t yy_nxt[2110] =
    {   0,
        4,    5,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   13,   13,   14,   14,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   14,   26,   27,
       28,   29,   30,   14,   31,   32,   33,   34,   35,   36,
       37,   14,   14,   14,   14,   38,   38,   40,  130,   41,
       41,   41,   41,   44,  435,   45,   45,   45,   45,   46,
       46,   46,   46,   42,   42,   47,   42,   48,   48,   48,
       49,   42,   42,   53,   42,  411,   53,   51,   54,   54,
       54,   54,   38,   38,   53,   51,   55,   55,   55,   55,
       46,   46,   46,   46,   52,   42,   42,   47,   42,   49,

       49,   49,   49,   50,   87,   50,   50,   81,   50,   51,
       50,  333,   83,   50,   82,   84,  235,  129,   50,   50,
       50,   50,   43,   56,   50,   43,   52,   53,   43,   50,
       50,   50,   50,   50,   99,  109,  449,   50,   50,  449,
       85,   86,   57,  100,  449,  449,   58,  449,   50,  101,
      449,   59,   60,  449,   61,  449,   62,   63,   42,   42,
       53,   42,   95,  110,  449,  111,   50,  112,  449,  449,
       96,   50,   51,   64,  449,   97,  132,  132,  132,   50,
      113,   98,   50,  125,   50,   50,  449,  126,   50,   50,
       65,   66,  449,   67,   50,  140,  449,   50,   68,   50,

       50,  449,   50,   50,   69,   50,  449,   70,   71,   42,
       42,   53,   42,  449,  122,  449,  127,  449,   50,  449,
      128,  138,   50,   51,   50,   50,  449,  123,   72,   50,
      124,  449,   73,   50,   40,   50,   41,   41,   41,   41,
       50,  449,  449,   74,   50,   75,  449,  449,   76,  449,
       50,  449,   77,  449,   50,   78,   79,   80,  449,   50,
       88,  449,   89,  135,   90,   50,  449,  141,   91,  142,
       92,   50,   50,   93,  449,  449,   50,   94,  449,   50,
       50,  102,   50,  449,   50,  449,  103,   50,  104,  105,
      449,  139,  106,  107,  148,  108,  114,  115,   50,  449,

      449,  116,   50,  449,  449,  117,   46,   46,   46,   46,
      449,  118,  119,   50,  120,   44,  121,   45,   45,   45,
       45,   46,   46,   46,   46,   46,   46,   46,   46,  236,
      236,  236,  449,  449,  449,  449,  129,   53,  449,   54,
       54,   54,   54,  449,  134,  449,   55,   55,   55,   55,
       50,  449,  143,  449,   50,  131,  133,  133,  133,  133,
      133,  133,  131,  449,  144,   50,   50,  133,  133,  133,
      133,  133,  133,   50,   50,   50,  449,   50,   50,  449,
      136,   50,  146,  137,   50,  145,   50,   50,   50,   50,
      449,   50,   50,   50,  149,  449,  157,   50,  449,   50,

       50,  147,   50,  158,  236,  236,  236,   50,   50,  150,
      159,   50,   50,   50,  151,  449,   50,   50,   50,  152,
      153,  154,   50,  155,  449,  156,   50,   50,   50,   50,
      160,  163,  162,   50,   50,   50,  449,   50,   50,   50,
      449,  449,  164,  449,   50,  161,  165,   50,   50,   50,
       50,   50,   50,  167,  169,  171,   50,   50,  449,   50,
       50,  172,   50,   50,  166,  168,  449,  449,   50,   50,
       50,  170,   50,   50,   50,   50,   50,  449,   50,   50,
      449,  174,   50,  449,  173,  176,  177,   50,  175,   50,
       50,   50,  449,  449,  449,   50,  178,   50,  179,  449,

      181,  449,  449,   50,   50,   50,   50,   50,   50,   50,
      180,   50,  449,  182,  449,  186,  449,   50,   50,   50,
       50,   50,  449,  183,  184,  185,   50,  187,  449,   50,
       50,   50,   50,   50,   50,   50,  191,   50,   50,  449,
      193,   50,   50,  189,   50,  188,   50,   50,  449,  194,
       50,   50,   50,   50,   50,  190,  192,  449,  449,   50,
      449,  449,   50,   50,  449,   50,   50,  195,  196,  449,
       50,  199,  197,  198,   50,   50,   50,  449,   50,   50,
       50,   50,   50,  204,   50,   50,  449,   50,   50,   50,
       50,  200,  205,  201,  202,  449,  449,  449,   50,   50,

      206,  203,   50,   50,  449,  449,   50,  208,   50,   50,
      449,  449,   50,   50,  449,  207,  209,   50,   50,  449,
      449,  210,  449,   50,   50,  211,  212,  449,  213,   50,
       50,  214,   50,   50,   50,  217,   50,   50,   50,  449,
      449,   50,   50,  449,   50,   50,  215,  216,  449,  219,
       50,  220,   50,   50,   50,   50,  449,  222,  218,   50,
       50,  449,  449,  449,   50,   50,  449,  221,  223,   50,
       50,  225,   50,   50,   50,   50,   50,  224,   50,  227,
      226,  449,   50,  449,   50,  449,   50,   50,  228,   50,
      229,   50,   50,  449,   50,   50,   50,   50,  230,   50,

       50,  231,  449,   50,   50,  232,   50,   50,  449,   50,
      449,  233,  234,  449,   50,   50,  449,  449,  449,  449,
      449,  235,  449,  449,  237,  237,  237,  237,  238,   50,
      449,   50,   50,   50,  449,   50,   50,   50,  239,  449,
       50,   50,  449,   50,   50,  240,   50,  449,  241,   50,
      449,   50,   50,   50,  131,  242,   50,  243,   50,  245,
       50,   50,   50,   50,   50,   50,  244,   50,   50,  449,
      247,   50,   50,   50,  449,  246,   50,  248,   50,  449,
       50,   50,  449,   50,   50,   50,   50,  449,  449,  250,
       50,  449,  251,   50,   50,   50,   50,   50,   50,  249,

       50,   50,  252,  449,   50,  449,   50,  253,   50,   50,
       50,  449,   50,   50,   50,   50,   50,   50,   50,  256,
      449,   50,  254,   50,  449,  449,   50,   50,   50,   50,
       50,  257,   50,  255,   50,   50,   50,  449,  259,   50,
      258,   50,   50,  260,   50,   50,   50,   50,   50,   50,
       50,   50,   50,  449,   50,  261,  262,   50,   50,   50,
       50,   50,  449,  449,   50,   50,   50,   50,   50,   50,
       50,   50,  449,  265,   50,   50,   50,   50,  263,   50,
      264,   50,  449,  266,   50,   50,   50,  268,   50,   50,
      267,   50,   50,  269,  270,  449,   50,   50,  449,   50,

       50,   50,   50,   50,   50,  271,   50,   50,  449,  272,
       50,   50,   50,  274,  449,   50,  449,   50,   50,   50,
      273,   50,   50,   50,  275,   50,   50,   50,   50,   50,
       50,   50,  449,  277,  449,  282,  449,   50,   50,  276,
       50,  278,  449,  279,  449,   50,   50,  280,  283,  281,
      286,   50,   50,  284,   50,   50,   50,   50,   50,  449,
      449,   50,  449,   50,  285,  449,   50,  449,  449,   50,
      287,   50,   50,   50,   50,   50,  288,   50,   50,   50,
       50,   50,  449,   50,   50,   50,   50,  449,  289,   50,
      449,  449,  449,  290,   50,   50,   50,  291,   50,   50,

       50,   50,   50,   50,  300,   50,  292,  294,   50,  293,
      449,  449,   50,   50,   50,   50,   50,  295,  449,  449,
      296,  301,  297,   50,   50,   50,  298,  449,  299,   50,
       50,  302,  303,  449,   50,   50,   50,   50,  449,  449,
       50,   50,  305,  449,   50,   50,   50,   50,   50,   50,
       50,  304,   50,   50,   50,  449,  449,  307,   50,   50,
      308,   50,  306,  449,   50,  309,   50,  449,  311,   50,
       50,   50,  449,  310,  449,   50,  449,  449,   50,   50,
       50,   50,   50,   50,   50,  312,   50,   50,  315,  313,
      449,   50,   50,   50,   50,   50,   50,   50,  449,  314,

       50,   50,   50,  319,   50,  318,  449,   50,  449,   50,
      316,  317,   50,   50,  449,   50,  449,   50,   50,   50,
       50,  449,   50,   50,  449,   50,   50,  449,   50,   50,
       50,   50,  320,   50,   50,   50,  322,  449,  321,  449,
       50,   50,  449,   50,  449,  323,   50,   50,   50,   50,
      324,  449,   50,   50,  325,  327,   50,   50,   50,  449,
       50,   50,  330,   50,   50,   50,   50,  328,  326,   50,
       50,   50,   50,   50,  329,   50,  449,   50,   50,   50,
       50,   50,   50,  449,  449,   50,  449,  449,  331,   50,
       50,  332,  334,   50,  237,  237,  237,  237,  336,  335,

       50,   50,   50,   50,  449,   50,   50,   50,  338,   50,
       50,  337,  449,   50,   50,   50,   50,   50,   50,   50,
      449,  340,   50,   50,   50,   50,   50,   50,  339,   50,
       50,   50,  449,   50,  449,   50,  341,   50,   50,  342,
      449,  343,  449,   50,   50,   50,   50,  344,   50,   50,
       50,   50,   50,  346,   50,   50,   50,  347,   50,  449,
      449,  449,  345,   50,   50,   50,   50,  348,   50,  449,
       50,   50,   50,   50,   50,   50,  351,   50,   50,  449,
       50,  449,   50,   50,  349,   50,   50,  350,   50,  449,
       50,   50,  449,   50,   50,   50,  352,   50,  449,   50,

       50,   50,   50,   50,   50,   50,   50,   50,  355,  353,
       50,  449,   50,  356,  354,   50,  449,   50,   50,  357,
       50,   50,  360,   50,   50,   50,   50,   50,   50,  358,
       50,  449,   50,  449,  449,   50,   50,  359,   50,  449,
       50,   50,   50,   50,   50,  449,   50,   50,  364,   50,
      449,   50,  449,   50,  362,   50,   50,   50,  449,  361,
       50,  363,   50,  365,   50,   50,   50,  449,  367,   50,
       50,   50,   50,  449,  369,  371,  449,  366,   50,   50,
       50,   50,  368,   50,  449,  449,  449,   50,  370,   50,
       50,   50,   50,   50,  449,   50,   50,   50,  376,   50,

       50,  372,   50,  449,   50,  449,  374,   50,   50,  373,
       50,  449,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,  375,   50,   50,   50,   50,   50,   50,   50,
       50,  449,  377,   50,   50,   50,  378,   50,  379,   50,
      385,   50,   50,   50,   50,  381,  449,  383,   50,   50,
      380,   50,   50,   50,   50,   50,   50,  449,  386,  382,
       50,  384,   50,  449,   50,   50,   50,   50,   50,   50,
       50,  387,   50,   50,  449,  449,   50,   50,  388,   50,
       50,   50,   50,  449,  390,   50,   50,   50,   50,   50,
       50,  449,  389,  449,   50,  449,  449,   50,   50,  392,

       50,  449,   50,   50,   50,   50,  391,   50,   50,  394,
       50,  393,   50,   50,   50,  449,   50,  396,   50,   50,
      449,   50,  449,  449,  395,   50,   50,   50,  449,   50,
       50,   50,   50,   50,   50,   50,  397,  449,   50,  449,
      449,   50,  449,   50,   50,  449,   50,   50,  398,   50,
       50,  400,   50,   50,  399,   50,   50,   50,   50,   50,
       50,  449,  449,  449,   50,   50,  449,   50,   50,  401,
       50,  449,   50,   50,  403,   50,   50,   50,   50,  402,
       50,  404,   50,  449,   50,  449,   50,   50,   50,   50,
      406,  449,  405,  449,   50,   50,  408,   50,   50,   50,

       50,  449,  449,  409,   50,  449,  407,  449,   50,   50,
      449,   50,  410,  449,   50,  410,  410,  410,  410,   50,
      412,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,  449,   50,  413,   50,   50,   50,   50,   50,
      449,  449,  449,   50,   50,   50,   50,   50,   50,   50,
      449,   50,   50,   50,  414,   50,   50,  415,   50,  449,
       50,   50,  449,   50,   50,   50,   50,  449,   50,  416,
       50,   50,   50,   50,   50,   50,   50,   50,  417,   50,
      449,   50,   50,   50,   50,   50,   50,   50,  449,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,

       50,   50,   50,  449,   50,   50,  449,  418,   50,   50,
       50,   50,   50,  419,  420,   50,   50,   50,   50,   50,
      421,   50,   50,   50,   50,  449,   50,   50,   50,   50,
       50,   50,   50,  449,   50,  449,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,  449,   50,  449,  449,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,  422,   50,  449,   50,   50,   50,   50,   50,   50,
       50,  449,  423,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,  424,   50,   50,

      449,   50,   50,  449,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,  449,   50,   50,  449,
       50,   50,   50,   50,  425,   50,   50,   50,  449,  426,
       50,   50,   50,   50,   50,   50,   50,   50,  449,   50,
       50,   50,   50,  449,  449,   50,  449,  428,  427,   50,
       50,   50,   50,   50,   50,  449,   50,   50,   50,   50,
       50,   50,  410,   50,   50,  410,  410,  410,  410,   50,
      429,   50,   50,  430,   50,  431,   50,   50,   50,   50,
       50,   50,   50,  433,   50,  449,  449,  449,   50,  432,
       50,   50,   50,   50,   50,  437,   50,   50,   50,   50,

       50,   50,  436,  434,   50,  449,   50,  449,   50,   50,
       50,   50,   50,   50,   50,  438,   50,   50,   50,   50,
       50,   50,  449,  439,  449,  449,   50,  449,   50,   50,
       50,   50,   50,  449,   50,  449,   50,  449,   50,   50,
       50,   50,   50,   50,   50,  441,   50,   50,  440,   50,
      449,  449,   50,  449,   50,   50,   50,   50,   50,  449,
       50,   50,   50,  442,   50,   50,   50,   50,   50,  449,
       50,  449,  443,   50,   50,   50,   50,  449,   50,  449,
       50,   50,   50,   50,   50,  449,   50,   50,  444,   50,
       50,   50,   50,  449,   50,   50,   50,   50,  445,   50,

       50,  449,   50,   50,   50,   50,  446,   50,   50,   50,
      449,  449,   50,   50,   50,   50,   50,  449,   50,  449,
       50,   50,   50,   50,   50,   50,   50,  447,  448,  449,
       50,   50,   50,   50,   50,   50,   50,  449,   50,   50,
      449,   50,  449,   50,  449,  449,  449,  449,  449,   50,
       50,   39,  449,   39,   39,   39,   42,   42,   50,   50,
       50,   51,   51,    3,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,

      449,  449,  449,  449,  449,  449,  449,  449,  449
    } ;

static yyconst flex_int16_t yy_chk[2110] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    7,  454,    7,
        7,    7,    7,    9,  411,    9,    9,    9,    9,   10,
       10,   10,   10,   12,   12,   12,   12,   12,   12,   12,
       12,   14,   14,   14,   14,  334,   15,   12,   15,   15,
       15,   15,   38,   38,   16,   14,   16,   16,   16,   16,
       40,   40,   40,   40,   12,   13,   13,   13,   13,   13,

       13,   13,   13,   24,   27,   15,   25,   24,   27,   13,
       25,  235,   25,   16,   24,   25,  129,   43,   24,   27,
       32,   25,   42,   17,   32,   11,   13,   19,    8,   19,
       19,   19,   19,   26,   30,   32,    3,   26,   30,    0,
       26,   26,   19,   30,    0,    0,   19,    0,   26,   30,
        0,   19,   19,    0,   19,    0,   19,   19,   20,   20,
       20,   20,   29,   33,    0,   33,   29,   33,    0,    0,
       29,   33,   20,   20,    0,   29,   48,   48,   48,   36,
       33,   29,   33,   36,   50,   61,    0,   36,   50,   61,
       20,   21,    0,   21,   36,   61,    0,   21,   21,   50,

       61,    0,   21,   21,   21,   21,    0,   21,   21,   22,
       22,   22,   22,    0,   35,    0,   37,    0,   35,    0,
       37,   59,   35,   22,   37,   59,    0,   35,   22,   59,
       35,    0,   22,   35,   41,   37,   41,   41,   41,   41,
       59,    0,    0,   22,   23,   23,    0,    0,   23,    0,
       57,    0,   23,    0,   57,   23,   23,   23,    0,   23,
       28,    0,   28,   57,   28,   57,    0,   62,   28,   62,
       28,   62,   60,   28,    0,    0,   60,   28,    0,   28,
       31,   31,   62,    0,   31,    0,   31,   60,   31,   31,
        0,   60,   31,   31,   67,   31,   34,   34,   67,    0,

        0,   34,   67,    0,    0,   34,   44,   44,   44,   44,
        0,   34,   34,   67,   34,   45,   34,   45,   45,   45,
       45,   46,   46,   46,   46,   47,   47,   47,   47,  132,
      132,  132,   53,   53,   53,   53,   44,   54,    0,   54,
       54,   54,   54,    0,   55,    0,   55,   55,   55,   55,
       63,    0,   63,    0,   63,   47,   52,   52,   52,   52,
       52,   52,   53,    0,   63,   63,   54,   52,   52,   52,
       52,   52,   52,   55,   58,   52,    0,   64,   58,    0,
       58,   64,   65,   58,   65,   64,   52,   66,   65,   58,
        0,   66,   64,   68,   68,    0,   70,   68,    0,   65,

       70,   66,   66,   71,  236,  236,  236,   71,   68,   69,
       72,   70,   72,   69,   69,    0,   72,   69,   71,   69,
       69,   69,   74,   69,    0,   69,   74,   72,   69,   73,
       73,   75,   74,   73,   76,   75,    0,   74,   76,   75,
        0,    0,   76,    0,   73,   73,   77,   77,   78,   76,
       75,   77,   78,   79,   80,   81,   80,   79,    0,   81,
       80,   81,   77,   78,   78,   79,    0,    0,   79,   82,
       81,   80,   83,   82,   84,   85,   83,    0,   84,   85,
        0,   83,   86,    0,   82,   85,   86,   83,   84,   84,
       85,   87,    0,    0,    0,   87,   86,   86,   86,    0,

       88,    0,    0,   88,   89,   90,   87,   88,   89,   90,
       87,   92,    0,   89,    0,   92,    0,   91,   88,   89,
       90,   91,    0,   90,   91,   91,   92,   93,    0,   93,
       94,   95,   91,   93,   94,   95,   97,   97,   99,    0,
       99,   97,   99,   95,   93,   94,   95,   96,    0,   99,
       98,   96,   97,   99,   98,   96,   98,    0,    0,  100,
        0,    0,   96,  100,    0,   98,  101,  100,  100,    0,
      101,  102,  101,  101,  100,  102,  103,    0,  104,  102,
      103,  101,  104,  106,  105,  107,    0,  106,  105,  107,
      102,  103,  106,  104,  105,    0,    0,    0,  106,  105,

      107,  105,  108,  109,    0,    0,  108,  109,  110,  111,
        0,    0,  110,  111,    0,  108,  110,  108,  109,    0,
        0,  110,    0,  110,  111,  111,  112,    0,  112,  113,
      112,  112,  114,  113,  112,  115,  114,  115,  116,    0,
        0,  115,  116,    0,  113,  112,  113,  114,    0,  117,
      117,  118,  115,  116,  117,  118,    0,  119,  116,  118,
      119,    0,    0,    0,  119,  117,    0,  118,  120,  121,
      118,  122,  120,  121,  122,  119,  120,  121,  122,  123,
      122,    0,  123,    0,  121,    0,  123,  120,  124,  122,
      125,  125,  124,    0,  126,  125,  124,  123,  126,  127,

      128,  126,    0,  127,  128,  127,  125,  124,    0,  126,
        0,  127,  128,    0,  127,  128,  130,  130,  130,  130,
      131,  131,  131,  131,  134,  134,  134,  134,  135,  136,
        0,  137,  135,  136,    0,  137,  138,  139,  136,    0,
      138,  139,    0,  135,  136,  137,  137,    0,  138,  140,
        0,  138,  139,  140,  134,  140,  142,  141,  143,  144,
      142,  141,  143,  144,  140,  141,  143,  144,  145,    0,
      145,  142,  145,  143,    0,  144,  141,  146,  144,    0,
      147,  146,    0,  145,  147,  146,  148,    0,    0,  149,
      148,    0,  150,  149,  150,  147,  146,  149,  150,  148,

      152,  148,  151,    0,  152,    0,  151,  152,  149,  150,
      151,    0,  153,  154,  155,  152,  153,  154,  155,  156,
        0,  151,  153,  156,    0,    0,  158,  153,  154,  155,
      158,  157,  159,  155,  156,  157,  159,    0,  159,  157,
      158,  158,  160,  160,  161,  162,  160,  159,  161,  162,
      157,  163,  164,    0,  165,  163,  164,  160,  165,  161,
      162,  166,    0,    0,  167,  166,  163,  164,  167,  165,
      170,  168,    0,  169,  170,  168,  166,  169,  167,  167,
      168,  169,    0,  170,  171,  170,  168,  172,  171,  173,
      171,  172,  169,  173,  174,    0,  175,  174,    0,  171,

      175,  174,  172,  176,  173,  175,  177,  176,    0,  176,
      177,  175,  174,  178,    0,  179,    0,  178,  176,  179,
      177,  177,  180,  181,  179,  182,  180,  181,  178,  182,
      179,  184,    0,  182,    0,  184,    0,  180,  181,  180,
      182,  183,    0,  183,    0,  183,  184,  183,  185,  183,
      187,  186,  185,  185,  187,  186,  183,  188,  187,    0,
        0,  188,    0,  185,  186,    0,  186,    0,    0,  187,
      188,  189,  188,  190,  191,  189,  189,  190,  191,  192,
      193,  194,    0,  192,  193,  194,  189,    0,  190,  191,
        0,    0,    0,  192,  192,  193,  194,  194,  195,  196,

      199,  197,  195,  196,  199,  197,  195,  197,  200,  196,
        0,    0,  200,  195,  196,  199,  197,  198,    0,    0,
      198,  200,  198,  200,  198,  201,  198,    0,  198,  201,
      202,  201,  203,    0,  202,  198,  203,  204,    0,    0,
      201,  204,  205,    0,  205,  202,  208,  203,  205,  206,
      208,  204,  204,  206,  207,    0,    0,  207,  207,  205,
      208,  208,  206,    0,  206,  209,  209,    0,  211,  207,
      209,  210,    0,  210,    0,  210,    0,    0,  211,  212,
      213,  209,  211,  212,  213,  212,  210,  214,  215,  213,
        0,  214,  215,  211,  212,  213,  215,  217,    0,  214,

      216,  217,  214,  219,  216,  218,    0,  215,    0,  218,
      216,  217,  217,  219,    0,  216,    0,  219,  220,  221,
      218,    0,  220,  221,    0,  222,  223,    0,  219,  222,
      223,  224,  220,  220,  221,  224,  223,    0,  222,    0,
      222,  223,    0,  225,    0,  224,  224,  225,  226,  227,
      225,    0,  226,  227,  226,  228,  229,  228,  225,    0,
      229,  228,  231,  226,  227,  230,  231,  228,  227,  230,
      231,  229,  228,  232,  230,  233,    0,  232,  234,  233,
      230,  231,  234,    0,    0,  238,    0,    0,  232,  238,
      233,  234,  237,  234,  237,  237,  237,  237,  239,  238,

      238,  239,  240,  241,    0,  239,  240,  241,  241,  242,
      244,  240,    0,  242,  244,  243,  239,  240,  241,  243,
        0,  243,  245,  246,  242,  244,  245,  246,  242,  247,
      243,  248,    0,  247,    0,  248,  245,  245,  246,  248,
        0,  249,    0,  250,  247,  249,  248,  250,  251,  252,
      253,  254,  251,  252,  253,  254,  249,  254,  250,    0,
        0,    0,  251,  251,  252,  253,  254,  255,  255,    0,
      256,  258,  255,  257,  256,  258,  259,  257,  260,    0,
      259,    0,  260,  255,  256,  256,  258,  257,  257,    0,
      261,  259,    0,  260,  261,  262,  261,  263,    0,  262,

      265,  263,  264,  266,  265,  261,  264,  266,  265,  262,
      262,    0,  263,  266,  264,  265,    0,  264,  266,  267,
      267,  268,  270,  269,  267,  268,  270,  269,  271,  268,
      270,    0,  271,    0,    0,  267,  268,  269,  269,    0,
      272,  270,  273,  271,  272,    0,  273,  274,  276,  276,
        0,  274,    0,  276,  275,  272,  275,  273,    0,  274,
      275,  275,  274,  277,  276,  277,  278,    0,  279,  277,
      278,  275,  279,    0,  280,  281,    0,  278,  280,  281,
      277,  278,  279,  279,    0,    0,    0,  282,  280,  280,
      281,  282,  283,  284,    0,  285,  283,  284,  288,  285,

      286,  282,  282,    0,  286,    0,  286,  283,  284,  285,
      285,    0,  287,  288,  290,  286,  287,  288,  290,  289,
      291,  292,  287,  289,  291,  292,  293,  287,  288,  290,
      293,    0,  289,  294,  289,  291,  292,  294,  295,  296,
      299,  293,  295,  296,  299,  297,    0,  298,  294,  297,
      296,  298,  300,  295,  296,  299,  300,    0,  300,  297,
      297,  298,  298,    0,  301,  302,  303,  300,  301,  302,
      303,  302,  304,  305,    0,    0,  304,  305,  303,  301,
      302,  303,  306,    0,  307,  308,  306,  304,  305,  308,
      309,    0,  306,    0,  309,    0,    0,  306,  307,  309,

      308,    0,  307,  310,  311,  309,  307,  310,  311,  311,
      312,  310,  313,  307,  312,    0,  313,  314,  310,  311,
        0,  314,    0,    0,  313,  312,  315,  313,    0,  316,
      315,  317,  314,  316,  318,  317,  315,    0,  318,    0,
        0,  315,    0,  319,  316,    0,  317,  319,  319,  318,
      320,  321,  322,  321,  320,  323,  322,  321,  319,  323,
      325,    0,    0,    0,  325,  320,    0,  322,  321,  324,
      323,    0,  326,  324,  327,  325,  326,  324,  327,  325,
      328,  328,  329,    0,  328,    0,  329,  326,  324,  327,
      329,    0,  328,    0,  330,  328,  331,  329,  330,  332,

      331,    0,    0,  332,  335,    0,  330,    0,  335,  330,
        0,  331,  333,    0,  332,  333,  333,  333,  333,  335,
      336,  337,  338,  339,  336,  337,  338,  339,  336,  340,
      341,  342,    0,  340,  341,  342,  337,  338,  339,  336,
        0,    0,    0,  343,  340,  341,  342,  343,  344,  345,
        0,  346,  344,  345,  344,  346,  347,  346,  343,    0,
      347,  348,    0,  344,  345,  348,  346,    0,  349,  350,
      351,  347,  349,  350,  351,  352,  348,  353,  351,  352,
        0,  353,  354,  349,  350,  351,  354,  355,    0,  356,
      352,  355,  353,  356,  357,  358,  359,  354,  357,  358,

      359,  360,  355,    0,  356,  360,    0,  360,  361,  357,
      358,  359,  361,  362,  363,  364,  360,  362,  363,  364,
      365,  362,  366,  361,  365,    0,  366,  367,  365,  363,
      364,  367,  362,    0,  368,    0,  369,  366,  368,  365,
      369,  370,  367,  371,  372,  370,  373,  371,  372,  368,
      373,  369,    0,  374,    0,    0,  370,  374,  371,  372,
      375,  373,  376,  377,  375,  378,  376,  377,  374,  378,
      379,  378,  380,    0,  379,  375,  380,  376,  377,  381,
      378,    0,  379,  381,  382,  379,  383,  380,  382,  384,
      383,  385,  386,  384,  381,  385,  386,  391,  387,  382,

        0,  383,  387,    0,  384,  388,  385,  386,  389,  388,
      390,  391,  389,  387,  390,  391,    0,  392,  393,    0,
      388,  392,  393,  389,  392,  390,  391,  394,    0,  395,
      395,  394,  392,  393,  395,  396,  397,  398,    0,  396,
      397,  398,  394,    0,    0,  395,    0,  399,  396,  399,
      396,  397,  398,  399,  400,    0,  401,  402,  400,  403,
      401,  402,  410,  403,  399,  410,  410,  410,  410,  400,
      401,  401,  402,  404,  403,  405,  406,  404,  407,  405,
      406,  404,  407,  407,  408,    0,    0,    0,  408,  406,
      405,  406,  404,  407,  409,  413,  412,  413,  409,  408,

      412,  413,  412,  409,  414,    0,  415,    0,  414,  409,
      415,  412,  413,  416,  418,  417,  417,  416,  418,  414,
      417,  415,    0,  419,    0,    0,  419,    0,  416,  418,
      419,  417,  420,    0,  421,    0,  420,    0,  421,  422,
      423,  419,  424,  422,  423,  422,  424,  420,  421,  421,
        0,    0,  425,    0,  422,  423,  425,  424,  426,    0,
      427,  428,  426,  427,  427,  428,  429,  425,  430,    0,
      429,    0,  430,  426,  431,  427,  428,    0,  431,    0,
      432,  429,  433,  430,  432,    0,  433,  436,  431,  431,
      434,  436,  437,    0,  434,  432,  437,  433,  434,  438,

      439,    0,  436,  438,  439,  434,  439,  437,  440,  441,
        0,    0,  440,  441,  438,  439,  442,    0,  444,    0,
      442,  443,  444,  440,  441,  443,  445,  443,  446,    0,
      445,  442,  446,  444,  447,  448,  443,    0,  447,  448,
        0,  445,    0,  446,    0,    0,    0,    0,    0,  447,
      448,  450,    0,  450,  450,  450,  451,  451,  452,  452,
      452,  453,  453,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,

      449,  449,  449,  449,  449,  449,  449,  449,  449
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[136] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ucode.l"
#line 2 "ucode.l"

// Igor Lopes - CS210 - HW#4

#include <stdio.h>
#include "ucode.tab.h"

#line 1111 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 12 "ucode.l"



#line 1329 "lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 450 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2064 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 15 "ucode.l"
{ 	      }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "ucode.l"
{	      }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 17 "ucode.l"
{ return VERSIONSTAMP; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 "ucode.l"
{ return UCODESTAMP; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 19 "ucode.l"
{ return OCTCONST; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 20 "ucode.l"
{ return DECCONST; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 21 "ucode.l"
{ return DECCONST; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 22 "ucode.l"
{ return COMMA; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 23 "ucode.l"
{ return CONTROL_L; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 24 "ucode.l"
{ return REALCONST; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 25 "ucode.l"
{ return FILENAME; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 26 "ucode.l"
{ return LABEL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 27 "ucode.l"
{ return ANY; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 28 "ucode.l"
{ return Op_Uid; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 29 "ucode.l"
{ return Op_Con; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 30 "ucode.l"
{ return Op_Impl;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 31 "ucode.l"
{ return Op_Bscan; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 32 "ucode.l"
{ return Op_Ccase; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 33 "ucode.l"
{ return Op_Chfail; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 34 "ucode.l"
{ return Op_Coact; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 35 "ucode.l"
{ return Op_Cofail; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 36 "ucode.l"
{ return Op_Coret; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 37 "ucode.l"
{ return Op_Create; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 38 "ucode.l"
{ return Op_Cset; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 39 "ucode.l"
{ return Op_Dup; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 40 "ucode.l"
{ return Op_Efail; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 41 "ucode.l"
{ return Op_EInit; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 42 "ucode.l"
{ return Op_Eret; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 43 "ucode.l"
{ return Op_Escan; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 44 "ucode.l"
{ return Op_Esusp; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 45 "ucode.l"
{ return Op_Field; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 46 "ucode.l"
{ return Op_Goto; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 47 "ucode.l"
{ return Op_Init; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 48 "ucode.l"
{ return Op_Int; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 49 "ucode.l"
{ return Op_Invoke; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 50 "ucode.l"
{ return Op_Keywd; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 51 "ucode.l"
{ return Op_Limit; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 52 "ucode.l"
{ return Op_Line; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 53 "ucode.l"
{ return Op_Llist; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 54 "ucode.l"
{ return Op_Lsusp; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 55 "ucode.l"
{ return Op_Mark; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 56 "ucode.l"
{ return Op_Pfail; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 57 "ucode.l"
{ return Op_Pnull; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 58 "ucode.l"
{ return Op_Pop; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 59 "ucode.l"
{ return Op_Pret; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 60 "ucode.l"
{ return Op_Psusp; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 61 "ucode.l"
{ return Op_Push1; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 62 "ucode.l"
{ return Op_Pushn1; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 63 "ucode.l"
{ return Op_Real; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 64 "ucode.l"
{ return Op_Sdup; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 65 "ucode.l"
{ return Op_Str; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 66 "ucode.l"
{ return Op_Unmark; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 67 "ucode.l"
{ return Op_Var; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 68 "ucode.l"
{ return Op_Arg; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 69 "ucode.l"
{ return Op_Static; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 70 "ucode.l"
{ return Op_Local; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 71 "ucode.l"
{ return Op_Global; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 72 "ucode.l"
{ return Op_Mark0; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 73 "ucode.l"
{ return Op_Quit; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 74 "ucode.l"
{ return Op_FQuit; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 75 "ucode.l"
{ return Op_Tally; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 76 "ucode.l"
{ return Op_Apply; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 77 "ucode.l"
{ return Op_Asgn; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 78 "ucode.l"
{ return Op_Bang; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 79 "ucode.l"
{ return Op_Cat; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 80 "ucode.l"
{ return Op_Compl; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 81 "ucode.l"
{ return Op_Diff; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 82 "ucode.l"
{ return Op_Div; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 83 "ucode.l"
{ return Op_Eqv; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 84 "ucode.l"
{ return Op_Inter; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 85 "ucode.l"
{ return Op_Lconcat; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 86 "ucode.l"
{ return Op_Lexeq; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 87 "ucode.l"
{ return Op_Lexge; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 88 "ucode.l"
{ return Op_Lexgt; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 89 "ucode.l"
{ return Op_Lexle; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 90 "ucode.l"
{ return Op_Lexlt; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 91 "ucode.l"
{ return Op_Lexne; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 92 "ucode.l"
{ return Op_Minus; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 93 "ucode.l"
{ return Op_Mod; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 94 "ucode.l"
{ return Op_Mult; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 95 "ucode.l"
{ return Op_Neg; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 96 "ucode.l"
{ return Op_Neqv; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 97 "ucode.l"
{ return Op_Nonnull; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 98 "ucode.l"
{ return Op_Null; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 99 "ucode.l"
{ return Op_Number; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 100 "ucode.l"
{ return Op_Numeq; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 101 "ucode.l"
{ return Op_Numge; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 102 "ucode.l"
{ return Op_Numgt; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 103 "ucode.l"
{ return Op_Numle; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 104 "ucode.l"
{ return Op_Numlt; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 105 "ucode.l"
{ return Op_Numne; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 106 "ucode.l"
{ return Op_Plus; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 107 "ucode.l"
{ return Op_Power; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 108 "ucode.l"
{ return Op_Random; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 109 "ucode.l"
{ return Op_Rasgn; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 110 "ucode.l"
{ return Op_Rcv; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 111 "ucode.l"
{ return Op_RcvBk; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 112 "ucode.l"
{ return Op_Refresh; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 113 "ucode.l"
{ return Op_Rswap; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 114 "ucode.l"
{ return Op_Sect; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 115 "ucode.l"
{ return Op_Snd; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 116 "ucode.l"
{ return Op_SndBk; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 117 "ucode.l"
{ return Op_Size; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 118 "ucode.l"
{ return Op_Subsc; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 119 "ucode.l"
{ return Op_Swap; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 120 "ucode.l"
{ return Op_Tabmat; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 121 "ucode.l"
{ return Op_Toby; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 122 "ucode.l"
{ return Op_Unions; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 123 "ucode.l"
{ return Op_Value; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 124 "ucode.l"
{ return Op_Acset; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 125 "ucode.l"
{ return Op_Areal; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 126 "ucode.l"
{ return Op_Astr; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 127 "ucode.l"
{ return Op_Aglobal; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 128 "ucode.l"
{ return Op_Astatic; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 129 "ucode.l"
{ return Op_Agoto; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 130 "ucode.l"
{ return Op_Amark; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 131 "ucode.l"
{ return Op_Noop; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 132 "ucode.l"
{ return Op_Colm; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 133 "ucode.l"
{ return Op_Proc; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 134 "ucode.l"
{ return Op_Declend; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 135 "ucode.l"
{ return Op_End; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 136 "ucode.l"
{ return Op_Link; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 137 "ucode.l"
{ return Op_Version; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 138 "ucode.l"
{ return Op_Filen; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 139 "ucode.l"
{ return Op_Record; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 140 "ucode.l"
{ return Op_Filen; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 141 "ucode.l"
{ return Op_Colm; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 142 "ucode.l"
{ return Op_Lab; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 143 "ucode.l"
{ return Op_Invocable; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 144 "ucode.l"
{ return Op_Copyd; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 145 "ucode.l"
{ return Op_Trapret; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 146 "ucode.l"
{ return Op_Trapfail; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 147 "ucode.l"
{ return Op_Synt; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 149 "ucode.l"
{ return IDENTIFIER; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 151 "ucode.l"
ECHO;
	YY_BREAK
#line 2072 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 450 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 450 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 449);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 150 "ucode.l"



