
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 135
#define YY_END_OF_BUFFER 136
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[449] =
    {   0,
        0,    0,  136,  135,    1,    9,  135,  135,    8,  135,
      135,  135,    6,    6,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,    1,    2,    0,
        6,    0,    0,    0,    6,   10,    0,    6,    6,  134,
      134,  134,    0,   12,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,

      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,    0,   11,   11,
        5,    7,    0,  134,  134,  134,  134,   13,  134,  134,
       54,  134,  134,  134,  134,   65,  134,  134,  134,  134,
      134,  134,   15,  134,  134,  134,  134,  134,  134,   68,
       25,  134,  134,  121,   69,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,   34,  134,  134,  128,
      134,  134,  134,  134,  134,  134,  134,  134,  134,   79,
      134,   81,  134,  134,  134,  134,  134,  134,  134,  134,

       44,  134,  134,  134,  134,  134,  134,  134,  134,   96,
      134,  134,  134,  134,  134,  134,  134,  101,  134,   51,
      134,  134,  134,  134,  134,  134,  134,   14,  134,  134,
      134,   53,  134,    0,    5,    0,  134,  134,  134,  134,
      134,  134,   63,  134,  112,   64,  134,  134,  134,  134,
      134,  118,  134,  134,  134,  134,   24,  134,   67,  134,
      134,   28,  134,  134,  134,  134,  134,  134,  134,   32,
       16,   33,  134,  134,  134,  134,  134,  134,  134,  134,
      134,   38,  122,  134,  134,  134,   41,  134,   80,   82,
      134,  117,   84,  134,  134,  134,  134,  134,  134,   92,

      134,  134,   45,  119,  134,  134,   59,  134,  134,  134,
       49,  134,  134,  134,   50,  100,  103,  134,  134,  134,
      105,  133,  134,  134,  107,  134,  134,  134,  134,  134,
      134,    0,    0,  110,  134,  115,  116,   62,  111,  134,
       17,   18,  134,   20,  134,   66,  130,   22,  134,  134,
       26,   27,  126,   29,   30,   31,  124,   60,  134,   70,
      134,  134,   36,  134,   72,   73,   74,   75,   76,   77,
       37,   39,   56,   40,   58,   78,  134,  134,   86,   87,
       88,   89,   90,   91,   42,   43,   93,   46,   47,  134,
      134,   95,   97,  134,  134,   99,  102,  134,  104,  134,

       61,  127,  134,  134,  134,  134,  109,  134,    4,    0,
      134,  134,   19,   21,   23,  134,   57,  134,   35,  134,
      134,   85,   48,   94,  125,  134,   55,  106,  134,  134,
      108,   52,  134,    3,  113,  114,  120,  134,   71,   83,
       98,  134,  131,  123,  134,  132,  129,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    5,    1,    1,    1,    1,    1,
        1,    1,    6,    7,    8,    9,   10,   11,   12,   13,
       13,   13,   13,   13,   13,   14,   14,    1,   10,    1,
        1,    1,    1,    1,   15,   16,   15,   15,   15,   15,
       17,   17,   17,   17,   17,   18,   17,   17,   17,   17,
       17,   17,   17,   17,   19,   17,   17,   17,   17,   17,
        1,   10,    1,    1,   20,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   17,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[46] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    3,    3,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    5,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4
    } ;

static yyconst flex_int16_t yy_base[454] =
    {   0,
        0,    0,  139, 2080,   44, 2080,    0,   39,  126,   45,
       49,  118,   57,   88,   65,   67,   75,    0,  117,  149,
      167,  199,  215,   78,  107,   84,   81,  235,  139,  108,
      251,   94,  142,  268,  189,  152,  191,   80,    0,   79,
      221,  113,   80,  291,  302,  306,  310,  163,    0,  196,
        0,  340,  327,  321,  333,  221,  343,  258,  346,  353,
      238,  360,  369,  372,  367,  389,  379,  409,  386,  388,
      408,  425,  418,  431,  430,  396,  432,  439,  452,  449,
      457,  459,  462,  465,  478,  481,  486,  495,  487,  507,
      508,  520,  513,  521,  526,  538,  539,  544,  552,  558,

      570,  568,  571,  577,  580,  578,  596,  597,  602,  603,
      624,  623,  626,  631,  632,  644,  649,  654,  666,  663,
      668,  676,  686,  685,  688,  693,  694,  103,  314,  724,
      185,    0,  728,  718,  719,  721,  726,  727,  740,  749,
      747,  748,  754,  757,  771,  770,  776,  777,  784,  783,
      790,  796,  803,  804,  809,  816,  821,  822,  829,  834,
      839,  841,  842,  847,  848,  855,  864,  871,  861,  877,
      878,  880,  890,  897,  885,  899,  904,  907,  917,  920,
      923,  937,  925,  942,  949,  954,  955,  956,  963,  972,
      975,  973,  980,  993,  994,  999, 1018, 1002, 1012, 1028,

     1031, 1036, 1038, 1041, 1044, 1058, 1050, 1067, 1068, 1084,
     1074, 1077, 1090, 1091, 1093, 1096, 1109, 1116, 1114, 1115,
     1121, 1122, 1135, 1138, 1140, 1143, 1156, 1148, 1161, 1168,
     1169, 1174, 1175,  103,  259, 1207, 1197, 1202, 1177, 1200,
     1203, 1210, 1209, 1219, 1226, 1227, 1228, 1235, 1240, 1245,
     1247, 1248, 1261, 1254, 1264, 1266, 1271, 1273, 1283, 1285,
     1290, 1292, 1297, 1295, 1311, 1314, 1316, 1319, 1332, 1302,
     1335, 1337, 1342, 1340, 1349, 1358, 1359, 1361, 1367, 1368,
     1380, 1385, 1386, 1388, 1393, 1405, 1410, 1413, 1407, 1412,
     1419, 1429, 1431, 1432, 1437, 1439, 1445, 1451, 1457, 1458,

     1464, 1465, 1467, 1474, 1481, 1497, 1483, 1495, 1503, 1509,
     1502, 1515, 1516, 1522, 1521, 1529, 1534, 1535, 1541, 1548,
     1543, 1551, 1557, 1560, 1565, 1567, 1573, 1583, 1589, 1590,
     1592, 1623,   94, 1599, 1617, 1615, 1616, 1618, 1623, 1624,
     1625, 1637, 1642, 1643, 1645, 1650, 1655, 1662, 1663, 1664,
     1669, 1671, 1676, 1681, 1683, 1688, 1689, 1690, 1695, 1702,
     1711, 1708, 1709, 1718, 1716, 1721, 1728, 1730, 1735, 1737,
     1738, 1740, 1747, 1754, 1756, 1757, 1759, 1764, 1766, 1773,
     1778, 1780, 1783, 1785, 1786, 1792, 1799, 1802, 1804, 1818,
     1809, 1811, 1821, 1828, 1831, 1830, 1837, 1849, 1850, 1855,

     1856, 1857, 1862, 1863, 1875, 1876, 1882, 1883, 1913,   44,
     1889, 1905, 1906, 1907, 1908, 1914, 1915, 1927, 1928, 1933,
     1934, 1935, 1941, 1951, 1953, 1958, 1959, 1960, 1965, 1967,
     1972, 1979, 1984, 2080, 1985, 1986, 1991, 1998, 1993, 2003,
     2005, 2010, 2011, 2017, 2019, 2024, 2027, 2080, 2067, 2070,
     2072, 2074,   45
    } ;

static yyconst flex_int16_t yy_def[454] =
    {   0,
      448,    1,  448,  448,  448,  448,  449,  448,  450,  450,
      448,  450,  451,  451,  451,   14,   14,  452,   14,  451,
       19,  451,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,  448,  449,  448,
      448,  450,  448,  448,  450,  448,  453,   14,   14,   22,
      452,   22,  453,   14,   14,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,  448,  453,  453,
       14,   52,  453,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,  448,   14,  448,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,  448,  448,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,  448,  448,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,  448,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,    0,  448,  448,
      448,  448,  448
    } ;

static yyconst flex_int16_t yy_nxt[2126] =
    {   0,
        4,    5,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   14,   14,   15,   15,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   15,   26,   27,
       28,   29,   30,   15,   31,   32,   33,   34,   35,   36,
       37,   15,   15,   15,   15,   38,   38,   40,  129,   41,
       41,   41,   41,   44,  434,   45,   45,   45,   45,   46,
       46,   46,   46,   42,   42,   47,   42,   48,   48,   48,
       49,   42,   42,   53,   42,   53,   51,   54,   54,   54,
       54,   38,   38,   53,   51,   55,   55,   55,   55,   46,
       46,   46,   46,   52,   42,   42,   47,   42,   49,   49,

       49,   49,   50,   50,  410,   86,   80,   51,   50,   50,
      332,   50,   50,   81,  234,   84,   85,   50,   50,  128,
       50,   43,   50,   50,   52,   53,   43,   50,   50,   50,
       50,   50,   98,  108,   43,   50,   50,   82,  448,   56,
       83,   99,  448,   57,  448,  448,   50,  100,   58,   59,
      448,   60,  448,   61,   62,   42,   42,   53,   42,   94,
      448,  448,  109,   50,  110,  448,  111,   95,   51,   63,
       50,  448,   96,  131,  131,  131,   50,  448,   97,  112,
      124,   50,  448,  448,  125,  448,   64,   65,  448,   66,
      448,   50,  448,   50,   67,  235,  235,  235,   50,   50,

       68,   50,  448,   69,   70,   42,   42,   53,   42,  121,
      448,  126,  448,   50,  448,  127,  448,   50,   51,   50,
       50,  448,  122,   71,   50,  123,  448,   72,   50,   40,
       50,   41,   41,   41,   41,   50,  448,  448,   73,   50,
       74,  448,  448,   75,  448,   50,  448,   76,  448,   50,
       77,   78,   79,  448,   50,   87,  448,   88,  134,   89,
       50,  448,  140,   90,  141,   91,   50,  448,   92,  235,
      235,  235,   93,  448,   50,   50,  101,   50,  137,   50,
      448,  102,   50,  103,  104,  448,   50,  105,  106,  448,
      107,  113,  114,  448,  448,  448,  115,   50,  448,  448,

      116,   46,   46,   46,   46,  448,  117,  118,  448,  119,
       44,  120,   45,   45,   45,   45,   46,   46,   46,   46,
       46,   46,   46,   46,  448,  448,  448,  448,  448,   53,
      128,   54,   54,   54,   54,  448,  448,  448,  448,  448,
      448,  133,  448,   55,   55,   55,   55,  448,  448,  130,
      132,  132,  132,  132,  132,  132,  448,   50,  448,  448,
      132,  132,  132,  132,  132,  132,  130,   50,   50,   50,
       50,   50,  448,  135,   50,  448,  136,   50,  448,   50,
      448,   50,   50,  448,   50,   50,  142,  139,   50,  138,
      448,   50,   50,   50,  145,   50,   50,   50,  143,   50,

       50,  144,  448,   50,  148,  146,   50,   50,   50,  147,
      156,   50,  157,   50,   50,  448,   50,   50,   50,  164,
       50,  448,  448,  448,   50,   50,  448,   50,   50,  149,
      158,  448,   50,   50,  150,   50,   50,   50,  448,  151,
      152,  153,   50,  154,  448,  155,   50,   50,   50,   50,
      159,  162,  161,   50,   50,   50,   50,   50,   50,   50,
       50,  448,  163,  166,   50,  160,  448,   50,  448,   50,
       50,   50,  165,  170,  168,  167,   50,   50,   50,  171,
       50,   50,  448,   50,  448,   50,   50,   50,   50,   50,
       50,  169,  173,   50,  448,  448,  172,  448,   50,  175,

      174,   50,   50,  448,   50,   50,  176,  180,  448,   50,
       50,   50,  448,  448,   50,   50,  177,   50,  178,   50,
       50,  448,  448,   50,  179,   50,   50,  448,  181,  182,
      448,   50,   50,  448,   50,   50,  185,   50,  183,  184,
      448,   50,  186,  448,   50,   50,   50,   50,   50,   50,
       50,  448,  187,  448,   50,  448,  448,  188,  189,   50,
       50,  190,   50,   50,  448,   50,   50,   50,   50,  191,
      192,  448,   50,  448,  448,  448,   50,   50,   50,  193,
       50,  448,   50,   50,  194,  195,   50,  448,  196,  197,
      198,   50,   50,  448,   50,   50,   50,   50,   50,   50,

      448,   50,   50,  448,  203,   50,   50,  199,   50,   50,
      200,  201,  448,  204,  448,  448,   50,  205,  202,   50,
       50,   50,  448,  448,   50,  207,   50,   50,  448,  448,
       50,   50,  448,  206,  208,   50,   50,  448,  448,  209,
      448,   50,   50,  210,  211,  448,  212,   50,   50,  213,
       50,   50,   50,  216,   50,   50,   50,  448,  448,   50,
       50,  448,   50,   50,  214,  215,  448,  218,   50,  219,
       50,   50,   50,   50,  448,  221,  217,   50,   50,  448,
      448,  448,   50,   50,  448,  220,  222,   50,   50,  224,
       50,   50,   50,   50,   50,  223,   50,  226,  225,  448,

       50,  448,   50,  448,   50,   50,  227,   50,  228,   50,
       50,  448,   50,   50,   50,   50,  229,   50,   50,  230,
      448,   50,   50,  231,   50,   50,  448,   50,  448,  232,
      233,  448,   50,   50,  448,  234,  448,  448,  236,  236,
      236,  236,  237,   50,  448,   50,   50,   50,  448,   50,
       50,   50,  238,  448,   50,   50,  448,   50,   50,  239,
       50,  448,  240,  448,   50,   50,   50,  130,   50,  242,
      241,   50,   50,   50,  244,   50,   50,   50,   50,   50,
      243,   50,   50,  246,  448,   50,   50,   50,   50,  448,
      245,  247,  448,   50,   50,   50,   50,  249,   50,   50,

       50,   50,  448,  251,   50,   50,  250,   50,   50,   50,
       50,   50,   50,  248,   50,   50,   50,  448,   50,  448,
       50,  252,   50,   50,   50,  448,  448,   50,   50,   50,
      253,   50,   50,  255,  448,   50,  256,   50,  448,  448,
       50,  448,   50,   50,   50,   50,   50,  254,   50,   50,
       50,  448,  258,   50,  259,   50,  448,   50,   50,  257,
       50,   50,   50,   50,  448,   50,   50,   50,   50,  260,
      261,   50,   50,   50,  448,   50,   50,  448,   50,   50,
       50,   50,  448,   50,  448,   50,   50,   50,   50,   50,
      448,  264,   50,  262,   50,   50,  448,  263,  265,   50,

       50,   50,  267,   50,   50,   50,   50,  266,  268,   50,
       50,  269,  448,   50,   50,  271,   50,   50,   50,   50,
      448,   50,  448,   50,   50,   50,  448,   50,  273,   50,
      270,   50,   50,  448,  448,   50,   50,  272,   50,  448,
      274,   50,  448,   50,   50,   50,   50,   50,   50,   50,
      448,   50,  448,  281,  448,  276,   50,  448,  275,   50,
      448,  277,   50,  278,   50,   50,  282,  279,  448,  280,
       50,  283,  448,   50,  285,  448,   50,   50,   50,   50,
       50,   50,   50,   50,   50,  287,  284,   50,   50,  448,
      448,   50,  286,   50,   50,   50,   50,   50,  448,   50,

       50,   50,  288,   50,   50,  448,  448,  448,   50,  448,
      448,   50,   50,  289,   50,  448,  448,   50,   50,   50,
      290,   50,   50,   50,  448,  291,   50,   50,  292,  293,
      299,  448,   50,   50,  448,  448,   50,  448,   50,  294,
       50,   50,  295,  448,  296,  448,   50,  448,  297,  300,
      298,   50,   50,  448,  448,   50,   50,   50,  301,   50,
      302,  448,   50,  304,   50,   50,   50,   50,   50,   50,
       50,  448,   50,  448,   50,   50,  303,   50,   50,  448,
       50,  305,   50,   50,  448,  306,   50,  448,  307,   50,
      308,   50,   50,  448,  309,   50,   50,   50,   50,  310,

      448,   50,   50,  448,  311,   50,   50,   50,   50,  448,
      312,  314,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,  448,   50,   50,  448,  313,  315,  448,   50,
       50,  318,   50,  317,  316,   50,  448,   50,   50,   50,
       50,  448,   50,   50,   50,   50,   50,  448,   50,   50,
       50,  448,  319,   50,   50,   50,  321,  448,  320,   50,
       50,   50,   50,   50,   50,  448,   50,   50,   50,  323,
      324,   50,   50,  322,   50,  448,   50,   50,  326,   50,
       50,  448,   50,  448,   50,   50,  325,   50,  329,   50,
      327,  448,   50,   50,  328,   50,   50,   50,   50,   50,

       50,   50,   50,   50,  448,   50,  448,   50,  330,  448,
      336,  448,  331,   50,   50,  333,   50,  236,  236,  236,
      236,   50,  448,  335,   50,   50,   50,   50,   50,  337,
       50,   50,  448,   50,   50,  334,   50,   50,   50,   50,
      339,   50,   50,   50,  448,  448,  338,   50,   50,   50,
       50,   50,   50,  448,   50,   50,   50,  340,   50,  342,
      341,  448,  448,   50,   50,   50,   50,   50,  343,   50,
      448,   50,   50,   50,   50,  345,   50,  347,   50,   50,
      448,  448,   50,  344,   50,   50,   50,   50,   50,   50,
       50,  346,   50,   50,   50,   50,  448,  350,  448,   50,

       50,   50,  348,   50,  349,   50,  448,   50,  448,   50,
       50,   50,   50,   50,   50,  351,   50,  448,   50,   50,
       50,   50,   50,   50,   50,   50,   50,  354,  352,   50,
       50,   50,  448,  353,   50,   50,   50,  356,   50,   50,
       50,   50,   50,   50,   50,  355,  448,   50,  357,  448,
       50,  448,  359,   50,  448,   50,   50,  358,   50,   50,
       50,   50,  361,   50,   50,   50,   50,  448,   50,  362,
       50,   50,  363,   50,   50,  448,   50,   50,  360,   50,
      364,   50,   50,   50,  448,  366,   50,   50,   50,   50,
      448,  368,  370,  448,  365,   50,   50,   50,   50,  367,

       50,  448,  448,  448,   50,  369,   50,   50,   50,   50,
       50,  448,   50,   50,   50,  448,   50,   50,  371,   50,
      375,   50,  448,  373,   50,   50,  372,   50,  448,   50,
      448,   50,   50,   50,   50,   50,   50,   50,   50,  374,
       50,   50,  448,   50,   50,  448,   50,   50,  448,   50,
      376,   50,   50,   50,  448,   50,  378,   50,  377,   50,
       50,   50,  448,  380,  448,   50,  448,   50,   50,  382,
       50,   50,  379,   50,  448,  384,   50,  381,   50,   50,
      448,   50,   50,  383,   50,   50,   50,  385,   50,   50,
       50,   50,   50,   50,  386,   50,   50,   50,   50,  448,

      448,  387,   50,   50,   50,   50,   50,   50,  389,   50,
      448,   50,  448,   50,  448,  388,  448,  448,  448,   50,
       50,   50,   50,   50,  448,   50,   50,   50,  391,  390,
       50,   50,  448,   50,   50,  392,   50,   50,  393,   50,
      395,   50,   50,   50,   50,   50,   50,  448,   50,   50,
       50,  394,  448,   50,   50,   50,  396,   50,   50,   50,
       50,   50,   50,   50,  397,   50,  448,   50,   50,  398,
      399,   50,   50,   50,   50,   50,   50,  400,  448,   50,
       50,   50,   50,  448,   50,   50,  448,   50,   50,   50,
       50,  402,  448,   50,  448,   50,   50,   50,  403,   50,

      448,   50,  448,  401,   50,  448,   50,   50,  448,  404,
      448,   50,   50,   50,  407,  405,   50,   50,   50,  448,
      408,  448,   50,   50,  448,  406,  448,   50,   50,   50,
      409,   50,  448,  409,  409,  409,  409,  411,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
      448,   50,  412,   50,   50,   50,   50,   50,  448,  448,
      448,   50,   50,   50,   50,   50,   50,   50,  448,   50,
       50,   50,  413,   50,   50,  414,   50,  448,   50,   50,
      448,   50,   50,   50,   50,  448,   50,  415,   50,   50,
       50,   50,   50,   50,   50,   50,  416,   50,  448,   50,

       50,   50,   50,   50,   50,   50,  448,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,  448,   50,   50,  448,  417,   50,   50,   50,   50,
       50,  418,  419,   50,   50,   50,   50,   50,  420,   50,
       50,   50,   50,  448,   50,   50,   50,   50,   50,   50,
       50,  448,   50,  448,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
      448,   50,  448,  448,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,  421,
       50,  448,   50,   50,   50,   50,   50,   50,   50,  448,

      422,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,  448,   50,   50,  448,   50,
       50,  448,   50,   50,   50,   50,   50,   50,   50,  423,
       50,   50,   50,   50,  448,   50,  448,   50,   50,   50,
      424,   50,   50,   50,  448,   50,   50,  448,   50,   50,
       50,  425,   50,  448,   50,   50,   50,   50,   50,   50,
       50,   50,  448,  448,  448,   50,  448,   50,  426,   50,
       50,  427,  448,   50,   50,  448,   50,   50,   50,   50,
       50,   50,  429,   50,   50,   50,   50,  430,   50,   50,
       50,   50,  448,  428,   50,   50,   50,  448,  448,   50,

       50,   50,   50,   50,   50,  432,   50,   50,  448,  448,
       50,   50,  431,   50,   50,   50,  433,   50,  448,  435,
      409,   50,   50,  409,  409,  409,  409,  436,   50,   50,
       50,   50,   50,   50,   50,   50,   50,  437,   50,   50,
      448,  448,   50,   50,   50,   50,   50,   50,  438,  448,
      448,   50,   50,   50,   50,   50,   50,   50,   50,   50,
      448,   50,   50,   50,  440,   50,   50,   50,  448,   50,
      448,  439,   50,   50,   50,   50,  448,   50,  448,   50,
       50,   50,   50,   50,   50,  441,   50,   50,   50,   50,
       50,   50,   50,  442,  448,   50,   50,   50,   50,   50,

       50,  448,  448,   50,   50,  443,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,  444,   50,   50,   50,
      448,   50,   50,   50,   50,   50,   50,   50,  445,   50,
       50,   50,   50,   50,   50,   50,  448,   50,   50,   50,
      446,   50,   50,  447,   50,   50,  448,   50,   50,   50,
       50,   50,   50,  448,  448,   50,   50,  448,   50,  448,
      448,  448,  448,   50,  448,  448,   50,   39,  448,   39,
       39,   39,   42,   42,   50,   50,   50,   51,   51,    3,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,

      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448
    } ;

static yyconst flex_int16_t yy_chk[2126] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    8,  453,    8,
        8,    8,    8,   10,  410,   10,   10,   10,   10,   11,
       11,   11,   11,   13,   13,   13,   13,   13,   13,   13,
       13,   15,   15,   15,   15,   16,   13,   16,   16,   16,
       16,   38,   38,   17,   15,   17,   17,   17,   17,   40,
       40,   40,   40,   13,   14,   14,   14,   14,   14,   14,

       14,   14,   24,   16,  333,   27,   24,   14,   26,   27,
      234,   17,   26,   24,  128,   26,   26,   24,   32,   43,
       27,   42,   32,   26,   14,   19,   12,   19,   19,   19,
       19,   25,   30,   32,    9,   25,   30,   25,    3,   19,
       25,   30,    0,   19,    0,    0,   25,   30,   19,   19,
        0,   19,    0,   19,   19,   20,   20,   20,   20,   29,
        0,    0,   33,   29,   33,    0,   33,   29,   20,   20,
       33,    0,   29,   48,   48,   48,   36,    0,   29,   33,
       36,   33,    0,    0,   36,    0,   20,   21,    0,   21,
        0,   36,    0,   21,   21,  131,  131,  131,   21,   21,

       21,   21,    0,   21,   21,   22,   22,   22,   22,   35,
        0,   37,    0,   35,    0,   37,    0,   35,   22,   37,
       50,    0,   35,   22,   50,   35,    0,   22,   35,   41,
       37,   41,   41,   41,   41,   50,    0,    0,   22,   23,
       23,    0,    0,   23,    0,   56,    0,   23,    0,   56,
       23,   23,   23,    0,   23,   28,    0,   28,   56,   28,
       56,    0,   61,   28,   61,   28,   61,    0,   28,  235,
      235,  235,   28,    0,   28,   31,   31,   61,   58,   31,
        0,   31,   58,   31,   31,    0,   58,   31,   31,    0,
       31,   34,   34,    0,    0,    0,   34,   58,    0,    0,

       34,   44,   44,   44,   44,    0,   34,   34,    0,   34,
       45,   34,   45,   45,   45,   45,   46,   46,   46,   46,
       47,   47,   47,   47,  129,  129,  129,  129,    0,   54,
       44,   54,   54,   54,   54,    0,    0,   53,   53,   53,
       53,   55,    0,   55,   55,   55,   55,    0,    0,   47,
       52,   52,   52,   52,   52,   52,    0,   54,    0,    0,
       52,   52,   52,   52,   52,   52,   53,   57,   52,   55,
       59,   57,    0,   57,   59,    0,   57,   60,    0,   52,
        0,   60,   57,    0,   62,   59,   62,   60,   62,   59,
        0,   65,   60,   63,   64,   65,   64,   63,   62,   62,

       64,   63,    0,   67,   67,   65,   65,   67,   63,   66,
       69,   64,   70,   66,   69,    0,   70,   66,   67,   76,
       76,    0,    0,    0,   76,   69,    0,   70,   66,   68,
       71,    0,   71,   68,   68,   76,   71,   68,    0,   68,
       68,   68,   73,   68,    0,   68,   73,   71,   68,   72,
       72,   74,   73,   72,   75,   74,   77,   73,   75,   74,
       77,    0,   75,   78,   72,   72,    0,   78,    0,   75,
       74,   77,   77,   80,   79,   78,   79,   80,   78,   80,
       79,   81,    0,   82,    0,   81,   83,   82,   80,   84,
       83,   79,   82,   84,    0,    0,   81,    0,   82,   84,

       83,   83,   85,    0,   84,   86,   85,   87,    0,   86,
       87,   89,    0,    0,   87,   89,   85,   85,   85,   88,
       86,    0,    0,   88,   86,   87,   89,    0,   88,   89,
        0,   90,   91,    0,   88,   90,   91,   93,   90,   90,
        0,   93,   92,    0,   92,   94,   90,   91,   92,   94,
       95,    0,   93,    0,   95,    0,    0,   94,   95,   92,
       94,   96,   96,   97,    0,   95,   96,   97,   98,   97,
       98,    0,   98,    0,    0,    0,   99,   96,   97,   98,
       99,    0,  100,   98,   99,   99,  100,    0,  100,  100,
      101,   99,  102,    0,  101,  103,  102,  100,  101,  103,

        0,  104,  106,    0,  105,  104,  106,  102,  105,  101,
      103,  104,    0,  105,    0,    0,  104,  106,  104,  105,
      107,  108,    0,    0,  107,  108,  109,  110,    0,    0,
      109,  110,    0,  107,  109,  107,  108,    0,    0,  109,
        0,  109,  110,  110,  111,    0,  111,  112,  111,  111,
      113,  112,  111,  114,  113,  114,  115,    0,    0,  114,
      115,    0,  112,  111,  112,  113,    0,  116,  116,  117,
      114,  115,  116,  117,    0,  118,  115,  117,  118,    0,
        0,    0,  118,  116,    0,  117,  119,  120,  117,  121,
      119,  120,  121,  118,  119,  120,  121,  122,  121,    0,

      122,    0,  120,    0,  122,  119,  123,  121,  124,  124,
      123,    0,  125,  124,  123,  122,  125,  126,  127,  125,
        0,  126,  127,  126,  124,  123,    0,  125,    0,  126,
      127,    0,  126,  127,  130,  130,  130,  130,  133,  133,
      133,  133,  134,  135,    0,  136,  134,  135,    0,  136,
      137,  138,  135,    0,  137,  138,    0,  134,  135,  136,
      136,    0,  137,    0,  139,  137,  138,  133,  139,  140,
      139,  141,  142,  140,  143,  141,  142,  140,  143,  139,
      142,  144,  143,  144,    0,  144,  141,  142,  140,    0,
      143,  145,    0,  143,  146,  145,  144,  148,  146,  145,

      147,  148,    0,  150,  147,  148,  149,  150,  149,  146,
      145,  150,  149,  147,  151,  147,  148,    0,  151,    0,
      152,  151,  150,  149,  152,    0,    0,  153,  154,  151,
      152,  153,  154,  155,    0,  152,  156,  155,    0,    0,
      156,    0,  153,  154,  156,  157,  158,  154,  155,  157,
      158,    0,  158,  159,  159,  156,    0,  159,  160,  157,
      157,  158,  160,  161,    0,  162,  163,  161,  159,  162,
      163,  164,  165,  160,    0,  164,  165,    0,  161,  166,
      162,  163,    0,  166,    0,  169,  164,  165,  167,  169,
        0,  168,  167,  166,  166,  168,    0,  167,  169,  168,

      169,  170,  171,  167,  172,  170,  171,  170,  172,  175,
      168,  173,    0,  175,  173,  175,  170,  171,  173,  172,
        0,  174,    0,  176,  175,  174,    0,  176,  177,  173,
      174,  178,  177,    0,    0,  178,  174,  176,  176,    0,
      178,  179,    0,  177,  180,  179,  178,  181,  180,  183,
        0,  181,    0,  183,    0,  181,  179,    0,  179,  180,
        0,  182,  181,  182,  183,  182,  184,  182,    0,  182,
      184,  184,    0,  185,  186,    0,  182,  185,  186,  187,
      188,  184,  186,  187,  188,  188,  185,  189,  185,    0,
        0,  189,  187,  186,  187,  188,  190,  192,    0,  191,

      190,  192,  189,  191,  193,    0,    0,    0,  193,    0,
        0,  190,  192,  191,  191,    0,    0,  194,  195,  193,
      193,  194,  195,  196,    0,  194,  198,  196,  195,  196,
      198,    0,  194,  195,    0,    0,  199,    0,  196,  197,
      199,  198,  197,    0,  197,    0,  197,    0,  197,  199,
      197,  199,  200,    0,    0,  201,  200,  197,  200,  201,
      202,    0,  203,  204,  202,  204,  203,  200,  205,  204,
      201,    0,  205,    0,  207,  202,  203,  203,  207,    0,
      204,  205,  206,  205,    0,  206,  206,    0,  207,  207,
      208,  208,  209,    0,  209,  208,  209,  206,  211,  210,

        0,  212,  211,    0,  211,  212,  208,  209,  210,    0,
      212,  214,  210,  211,  213,  214,  212,  215,  213,  214,
      216,  215,    0,  210,  216,    0,  213,  215,    0,  213,
      214,  218,  215,  217,  216,  216,    0,  217,  219,  220,
      218,    0,  219,  220,  218,  221,  222,    0,  217,  221,
      222,    0,  219,  219,  220,  218,  222,    0,  221,  223,
      221,  222,  224,  223,  225,    0,  224,  226,  225,  224,
      225,  226,  228,  223,  223,    0,  228,  224,  227,  225,
      227,    0,  226,    0,  227,  229,  226,  228,  230,  229,
      227,    0,  230,  231,  229,  227,  230,  231,  232,  233,

      229,  239,  232,  233,    0,  239,    0,  230,  231,    0,
      239,    0,  233,  232,  233,  236,  239,  236,  236,  236,
      236,  237,    0,  238,  240,  237,  238,  241,  240,  240,
      238,  241,    0,  243,  242,  237,  237,  243,  242,  240,
      242,  238,  241,  244,    0,    0,  241,  244,  243,  242,
      245,  246,  247,    0,  245,  246,  247,  244,  244,  248,
      247,    0,    0,  248,  249,  245,  246,  247,  249,  250,
        0,  251,  252,  250,  248,  251,  252,  254,  254,  249,
        0,    0,  254,  250,  250,  253,  251,  252,  255,  253,
      256,  253,  255,  254,  256,  257,    0,  258,    0,  257,

      253,  258,  255,  255,  256,  256,    0,  259,    0,  260,
      257,  259,  258,  260,  261,  260,  262,    0,  261,  264,
      262,  263,  259,  264,  260,  263,  270,  264,  261,  261,
      270,  262,    0,  263,  264,  265,  263,  266,  266,  265,
      267,  270,  266,  268,  267,  265,    0,  268,  267,    0,
      265,    0,  269,  266,    0,  267,  269,  268,  268,  271,
      269,  272,  274,  271,  274,  272,  273,    0,  274,  274,
      273,  269,  275,  275,  271,    0,  272,  275,  273,  274,
      276,  273,  276,  277,    0,  278,  276,  277,  275,  278,
        0,  279,  280,    0,  277,  279,  280,  276,  277,  278,

      278,    0,    0,    0,  281,  279,  279,  280,  281,  282,
      283,    0,  284,  282,  283,    0,  284,  285,  281,  281,
      287,  285,    0,  285,  282,  283,  284,  284,    0,  286,
        0,  289,  285,  286,  287,  289,  290,  288,  287,  286,
      290,  288,    0,  291,  286,    0,  289,  291,    0,  287,
      288,  290,  288,  292,    0,  293,  294,  292,  291,  293,
      294,  295,    0,  296,    0,  295,    0,  296,  292,  297,
      293,  294,  295,  297,    0,  298,  295,  296,  296,  298,
        0,  299,  300,  297,  297,  299,  300,  299,  301,  302,
      298,  303,  301,  302,  301,  303,  299,  300,  304,    0,

        0,  302,  304,  301,  302,  305,  303,  307,  306,  305,
        0,  307,    0,  304,    0,  305,    0,    0,    0,  308,
      305,  306,  307,  308,    0,  306,  311,  309,  308,  306,
      311,  309,    0,  310,  308,  309,  306,  310,  310,  312,
      313,  311,  309,  312,  313,  315,  314,    0,  310,  315,
      314,  312,    0,  316,  312,  313,  314,  316,  317,  318,
      315,  314,  317,  318,  318,  319,    0,  321,  316,  319,
      320,  321,  320,  317,  318,  322,  320,  323,    0,  322,
      319,  323,  321,    0,  324,  323,    0,  320,  324,  325,
      322,  326,    0,  325,    0,  326,  323,  327,  327,  324,

        0,  327,    0,  324,  325,    0,  326,  328,    0,  327,
        0,  328,  327,  329,  330,  328,  331,  329,  330,    0,
      331,    0,  328,  334,    0,  329,    0,  334,  329,  330,
      332,  331,    0,  332,  332,  332,  332,  335,  334,  336,
      337,  335,  338,  336,  337,  335,  338,  339,  340,  341,
        0,  339,  340,  341,  336,  337,  335,  338,    0,    0,
        0,  342,  339,  340,  341,  342,  343,  344,    0,  345,
      343,  344,  343,  345,  346,  345,  342,    0,  346,  347,
        0,  343,  344,  347,  345,    0,  348,  349,  350,  346,
      348,  349,  350,  351,  347,  352,  350,  351,    0,  352,

      353,  348,  349,  350,  353,  354,    0,  355,  351,  354,
      352,  355,  356,  357,  358,  353,  356,  357,  358,  359,
      354,    0,  355,  359,    0,  359,  360,  356,  357,  358,
      360,  361,  362,  363,  359,  361,  362,  363,  364,  361,
      365,  360,  364,    0,  365,  366,  364,  362,  363,  366,
      361,    0,  367,    0,  368,  365,  367,  364,  368,  369,
      366,  370,  371,  369,  372,  370,  371,  367,  372,  368,
        0,  373,    0,    0,  369,  373,  370,  371,  374,  372,
      375,  376,  374,  377,  375,  376,  373,  377,  378,  377,
      379,    0,  378,  374,  379,  375,  376,  380,  377,    0,

      378,  380,  381,  378,  382,  379,  381,  383,  382,  384,
      385,  383,  380,  384,  385,    0,  386,  381,    0,  382,
      386,    0,  383,  387,  384,  385,  388,  387,  389,  390,
      388,  386,  389,  391,    0,  392,    0,  391,  387,  392,
      391,  388,  390,  389,    0,  393,  390,    0,  391,  393,
      392,  394,  394,    0,  396,  395,  394,  390,  396,  395,
      393,  397,    0,    0,    0,  397,    0,  394,  395,  396,
      395,  398,    0,  398,  399,    0,  397,  398,  399,  400,
      401,  402,  403,  400,  401,  402,  403,  404,  398,  399,
      403,  404,    0,  400,  400,  401,  402,    0,    0,  405,

      406,  403,  404,  405,  406,  406,  407,  408,    0,    0,
      407,  408,  405,  411,  405,  406,  408,  411,    0,  411,
      409,  407,  408,  409,  409,  409,  409,  412,  411,  412,
      413,  414,  415,  412,  413,  414,  415,  416,  416,  417,
        0,    0,  416,  417,  412,  413,  414,  415,  418,    0,
        0,  418,  419,  416,  417,  418,  419,  420,  421,  422,
        0,  420,  421,  422,  421,  423,  418,  419,    0,  423,
        0,  420,  420,  421,  422,  424,    0,  425,    0,  424,
      423,  425,  426,  427,  428,  426,  426,  427,  428,  429,
      424,  430,  425,  429,    0,  430,  431,  426,  427,  428,

      431,    0,    0,  432,  429,  430,  430,  432,  433,  435,
      436,  431,  433,  435,  436,  437,  433,  439,  432,  437,
        0,  439,  438,  433,  435,  436,  438,  440,  438,  441,
      437,  440,  439,  441,  442,  443,    0,  438,  442,  443,
      442,  444,  440,  445,  441,  444,    0,  445,  446,  442,
      443,  447,  446,    0,    0,  447,  444,    0,  445,    0,
        0,    0,    0,  446,    0,    0,  447,  449,    0,  449,
      449,  449,  450,  450,  451,  451,  451,  452,  452,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,

      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[136] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "hw4.l"
#line 2 "hw4.l"

// Igor Lopes - CS210 - HW#4

#include <stdio.h>
#include "hw4.h"
#line 1114 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 11 "hw4.l"



#line 1332 "lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 449 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2080 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 14 "hw4.l"
{ 	      }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 15 "hw4.l"
{	      }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 16 "hw4.l"
{ return VERSIONSTAMP; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 17 "hw4.l"
{ return UCODESTAMP; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 18 "hw4.l"
{ return OCTCONST; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 19 "hw4.l"
{ return DECCONST; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 20 "hw4.l"
{ return DECCONST; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 21 "hw4.l"
{ return COMMA; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 22 "hw4.l"
{ return CONTROL_L; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 23 "hw4.l"
{ return REALCONST; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 24 "hw4.l"
{ return FILENAME; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 25 "hw4.l"
{ return LABEL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 26 "hw4.l"
{ return ANY; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 27 "hw4.l"
{ return Op_Uid; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 28 "hw4.l"
{ return Op_Con; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 29 "hw4.l"
{ return Op_Impl;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 30 "hw4.l"
{ return Op_Bscan; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 31 "hw4.l"
{ return Op_Ccase; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 32 "hw4.l"
{ return Op_Chfail; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 33 "hw4.l"
{ return Op_Coact; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 34 "hw4.l"
{ return Op_Cofail; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 35 "hw4.l"
{ return Op_Coret; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 36 "hw4.l"
{ return Op_Create; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 37 "hw4.l"
{ return Op_Cset; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 38 "hw4.l"
{ return Op_Dup; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 39 "hw4.l"
{ return Op_Efail; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 40 "hw4.l"
{ return Op_EInit; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 41 "hw4.l"
{ return Op_Eret; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 42 "hw4.l"
{ return Op_Escan; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 43 "hw4.l"
{ return Op_Esusp; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 44 "hw4.l"
{ return Op_Field; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 45 "hw4.l"
{ return Op_Goto; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 46 "hw4.l"
{ return Op_Init; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 47 "hw4.l"
{ return Op_Int; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 48 "hw4.l"
{ return Op_Invoke; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 49 "hw4.l"
{ return Op_Keywd; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 50 "hw4.l"
{ return Op_Limit; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 51 "hw4.l"
{ return Op_Line; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 52 "hw4.l"
{ return Op_Llist; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 53 "hw4.l"
{ return Op_Lsusp; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 54 "hw4.l"
{ return Op_Mark; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 55 "hw4.l"
{ return Op_Pfail; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 56 "hw4.l"
{ return Op_Pnull; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 57 "hw4.l"
{ return Op_Pop; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 58 "hw4.l"
{ return Op_Pret; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 59 "hw4.l"
{ return Op_Psusp; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 60 "hw4.l"
{ return Op_Push1; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 61 "hw4.l"
{ return Op_Pushn1; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 62 "hw4.l"
{ return Op_Real; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 63 "hw4.l"
{ return Op_Sdup; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 64 "hw4.l"
{ return Op_Str; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 65 "hw4.l"
{ return Op_Unmark; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 66 "hw4.l"
{ return Op_Var; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 67 "hw4.l"
{ return Op_Arg; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 68 "hw4.l"
{ return Op_Static; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 69 "hw4.l"
{ return Op_Local; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 70 "hw4.l"
{ return Op_Global; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 71 "hw4.l"
{ return Op_Mark0; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 72 "hw4.l"
{ return Op_Quit; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 73 "hw4.l"
{ return Op_FQuit; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 74 "hw4.l"
{ return Op_Tally; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 75 "hw4.l"
{ return Op_Apply; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 76 "hw4.l"
{ return Op_Asgn; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 77 "hw4.l"
{ return Op_Bang; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 78 "hw4.l"
{ return Op_Cat; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 79 "hw4.l"
{ return Op_Compl; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 80 "hw4.l"
{ return Op_Diff; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 81 "hw4.l"
{ return Op_Div; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 82 "hw4.l"
{ return Op_Eqv; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 83 "hw4.l"
{ return Op_Inter; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 84 "hw4.l"
{ return Op_Lconcat; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 85 "hw4.l"
{ return Op_Lexeq; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 86 "hw4.l"
{ return Op_Lexge; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 87 "hw4.l"
{ return Op_Lexgt; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 88 "hw4.l"
{ return Op_Lexle; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 89 "hw4.l"
{ return Op_Lexlt; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 90 "hw4.l"
{ return Op_Lexne; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 91 "hw4.l"
{ return Op_Minus; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 92 "hw4.l"
{ return Op_Mod; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 93 "hw4.l"
{ return Op_Mult; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 94 "hw4.l"
{ return Op_Neg; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 95 "hw4.l"
{ return Op_Neqv; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 96 "hw4.l"
{ return Op_Nonnull; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 97 "hw4.l"
{ return Op_Null; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 98 "hw4.l"
{ return Op_Number; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 99 "hw4.l"
{ return Op_Numeq; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 100 "hw4.l"
{ return Op_Numge; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 101 "hw4.l"
{ return Op_Numgt; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 102 "hw4.l"
{ return Op_Numle; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 103 "hw4.l"
{ return Op_Numlt; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 104 "hw4.l"
{ return Op_Numne; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 105 "hw4.l"
{ return Op_Plus; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 106 "hw4.l"
{ return Op_Power; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 107 "hw4.l"
{ return Op_Random; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 108 "hw4.l"
{ return Op_Rasgn; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 109 "hw4.l"
{ return Op_Rcv; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 110 "hw4.l"
{ return Op_RcvBk; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 111 "hw4.l"
{ return Op_Refresh; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 112 "hw4.l"
{ return Op_Rswap; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 113 "hw4.l"
{ return Op_Sect; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 114 "hw4.l"
{ return Op_Snd; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 115 "hw4.l"
{ return Op_SndBk; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 116 "hw4.l"
{ return Op_Size; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 117 "hw4.l"
{ return Op_Subsc; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 118 "hw4.l"
{ return Op_Swap; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 119 "hw4.l"
{ return Op_Tabmat; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 120 "hw4.l"
{ return Op_Toby; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 121 "hw4.l"
{ return Op_Unions; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 122 "hw4.l"
{ return Op_Value; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 123 "hw4.l"
{ return Op_Acset; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 124 "hw4.l"
{ return Op_Areal; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 125 "hw4.l"
{ return Op_Astr; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 126 "hw4.l"
{ return Op_Aglobal; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 127 "hw4.l"
{ return Op_Astatic; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 128 "hw4.l"
{ return Op_Agoto; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 129 "hw4.l"
{ return Op_Amark; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 130 "hw4.l"
{ return Op_Noop; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 131 "hw4.l"
{ return Op_Colm; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 132 "hw4.l"
{ return Op_Proc; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 133 "hw4.l"
{ return Op_Declend; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 134 "hw4.l"
{ return Op_End; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 135 "hw4.l"
{ return Op_Link; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 136 "hw4.l"
{ return Op_Version; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 137 "hw4.l"
{ return Op_Filen; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 138 "hw4.l"
{ return Op_Record; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 139 "hw4.l"
{ return Op_Filen; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 140 "hw4.l"
{ return Op_Colm; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 141 "hw4.l"
{ return Op_Lab; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 142 "hw4.l"
{ return Op_Invocable; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 143 "hw4.l"
{ return Op_Copyd; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 144 "hw4.l"
{ return Op_Trapret; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 145 "hw4.l"
{ return Op_Trapfail; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 146 "hw4.l"
{ return Op_Synt; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 148 "hw4.l"
{ return IDENTIFIER; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 150 "hw4.l"
ECHO;
	YY_BREAK
#line 2075 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 449 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 449 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 448);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 149 "hw4.l"



